name: CrystaliaUHC
author: Luclyoko
version: 1.0-SNAPSHOT
description: Plugin UHC du serveur Crystalia
main: fr.luclyoko.crystaliauhc.Main
load: STARTUP
commands:
  host:
    aliases:
      - h
    usage: /host <config;op;deop;spec>
    description: Commande d'administration de la partie.
  map:
    usage: /map <radius>
    description: Commande temporaire de prégénération.